spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Ha@2405
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  cache:
    type: simple
  batch:
    job:
      enabled: false
    initialize-schema: always
logging:
  level:
    root: INFO
    com.example.bookcrud: DEBUG
server:
  port: 8080
  logging:
    level:
      root: INFO
      com.example.bookcrud: DEBUG
      org.springframework.web: DEBUG